module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "danger-50": "var(--danger-50)",
        "danger-500": "var(--danger-500)",
        "gray-00": "var(--gray-00)",
        "gray-100": "var(--gray-100)",
        "gray-200": "var(--gray-200)",
        "gray-300": "var(--gray-300)",
        "gray-400": "var(--gray-400)",
        "gray-50": "var(--gray-50)",
        "gray-500": "var(--gray-500)",
        "gray-600": "var(--gray-600)",
        "gray-700": "var(--gray-700)",
        "gray-900": "var(--gray-900)",
        "gray-scale500": "var(--gray-scale500)",
        "gray-scale600": "var(--gray-scale600)",
        "gray-scale700": "var(--gray-scale700)",
        "gray-scale900": "var(--gray-scale900)",
        "gray-scalewhite": "var(--gray-scalewhite)",
        graywhite: "var(--graywhite)",
        "primary-200": "var(--primary-200)",
        "primary-50": "var(--primary-50)",
        "primary-500": "var(--primary-500)",
        "success-50": "var(--success-50)",
        "success-500": "var(--success-500)",
        "warning-100": "var(--warning-100)",
        "warning-200": "var(--warning-200)",
        "warning-300": "var(--warning-300)",
        "warning-500": "var(--warning-500)",
        "warning-600": "var(--warning-600)",
        "warning-800": "var(--warning-800)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "body-large-400": "var(--body-large-400-font-family)",
        "body-large-500": "var(--body-large-500-font-family)",
        "body-medium-400": "var(--body-medium-400-font-family)",
        "body-medium-500": "var(--body-medium-500-font-family)",
        "body-small-400": "var(--body-small-400-font-family)",
        "body-small-500": "var(--body-small-500-font-family)",
        "body-XL-500": "var(--body-XL-500-font-family)",
        "button-button": "var(--button-button-font-family)",
        "display-01": "var(--display-01-font-family)",
        "heading-01": "var(--heading-01-font-family)",
        "heading-03": "var(--heading-03-font-family)",
        "heading-04": "var(--heading-04-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        "hover-shadow-primary": "var(--hover-shadow-primary)",
        "search-shadow": "var(--search-shadow)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
